base:
  project_name: mlops framework
  random_state: 42

training:
  epochs: 10
  batch_size: 32
  lr: 0.001

logging:
  metrics_dir: results/metrics
  metrics_path: metrics_001.json
  model_dir: results/saved_models
  model_path: model_001.pt

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: cnn
  run_name: mlops_001
  registered_model_path: cnn_model
  remote_server_uri: http://0.0.0.0:1234
